services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoceste_backend
    ports:
      - "18080:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/autocesteBazaPodataka
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.4-alpine
    container_name: autoceste_postgres_db
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_PASSWORD=database
      - POSTGRES_USER=postgres
      - POSTGRES_DB=autocesteBazaPodataka
    healthcheck:
      test: [ "CMD" , "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 30

  frontend:
    image: "autocestefrontend_frontend"
    container_name: "autoceste_frontend"
    ports:
      - "80:80"
    depends_on:
      - app